[package]
name = "calmare"
version = "0.1.0"
edition = "2021"

[dependencies]
themelios.workspace = true
extend = "1.2.0"
unicode-ident = "1.0.12"
bimap = "0.6.3"

[dev-dependencies]
anyhow = "1.0.79"
compact-debug = "0.1.0"
similar-asserts = "1.5.0"

