[workspace]
members = [
	"themelios",
	"themelios-gamedata",
	"calmare",
	"examples",
]
resolver = "2"

[workspace.dependencies]
themelios = { path = "./themelios" }
themelios-gamedata = { path = "./themelios-gamedata" }
calmare = { path = "./calmare" }
