[package]
name = "themelios"
version = "0.1.0"
edition = "2021"

[dependencies]
themelios-gamedata.workspace = true

gospel = "0.3.0"
strict_result = "1.2.0"
falcom-sjis = "0.1.1"

extend = "1.2.0"
glam = { version = "0.24.2", features = ["serde"] }
num_enum = "0.7.1"
thiserror = "1.0.51"
