[package]
name = "examples"
version = "0.0.0"
edition = "2021"

[dev-dependencies]
themelios.workspace = true
calmare.workspace = true
anyhow = "1.0"
compact-debug = "0.1.0"
codespan-reporting = "0.11.1"
